BBMS/urls.py
from django.contrib import admin
from django.urls import path
from .views import *


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index, name='index'),
    path('about/',about,name='about'),
    path('index_about',index_about,name='index_about'),
    
    path('donor/',donor,name='donor'),
    path('bloodrequest/',bloodrequest,name='bloodrequest'),
    path('register/',register, name='register'),
    path('register/auth/', AuthView.as_view(), name='auth'),
    path('login/',user_login, name='login'),
    
    path('logout/', logout, name='logout'),
    
    path('admin/logout/', custom_logout, name='custom_logout'),
    
    path('dashboard/',dashboard,name='dashboard'),
    path('landing_page/',landing_page,name='landing_page'),
    path('index/',index,name='index'),

    
    path('donors/<pk>/delete',delete_donor),
    path('receipent/<pk>/delete',delete_receipent),
    
    path('donor/<pk>/edit_donor',edit_donor),
    path('receipent/<pk>/edit_receipent',edit_receipent),

     
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



     
     

project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('BBMS.urls')),
    

    
    
    
    
    
]

BBMS/models.py
from django.db import models
from django.contrib.auth import get_user_model

User=get_user_model()
class Donor(models.Model):
    Donor_Name = models.CharField(max_length=100)
    Donor_Age = models.IntegerField(default=10)
    Donor_Address=models.CharField(max_length=100)
    Donor_BloodType = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True)
    Donor_Email=models.CharField(max_length=100)
    Donor_Phone=models.BigIntegerField(default=10)
    Donor_DateTime = models.DateTimeField(auto_now_add=True)

    

class Receipent(models.Model):
    Receipent_Name = models.CharField(max_length=100)
    Receipent_Age = models.IntegerField(default=10)
    Receipent_BloodType = models.CharField(max_length=50)
    Receipent_Address = models.CharField(max_length=50)
    Receipent_Email = models.CharField(max_length=50)
    Receipent_Phone= models.BigIntegerField(default=50)
    Receipent_Hospital= models.CharField(max_length=50)
    Receipent_DateTime = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True)

    def __str__(self):
        return self.Receipent_Name

class BloodBank(models.Model):
    BloodBank_Order = models.CharField(max_length=100)
    BloodBank_Bloodtype = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True)

    def __str__(self):
        return self.BloodBank_Order

    
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='profile_photos', blank=True, null=True)

    def __str__(self):
        return f'Profile of {self.user.username}'
    

templates/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MeroBloodBank</title>
 
    <link rel="stylesheet" type="text/css" href="{% static 'css/about.css' %}" />
</head>
<body>
    <nav>
        <a class="logo" href="{% url 'landing_page'%}">
            <img src="{% static 'image/blood.png' %}" alt="" srcset="" />
          MeroBloodBank</a>
        <div>
            <a href="{% url 'about'%}">About</a>
            <a href="{% url 'donor'%}">Donor</a>
            <a href="{% url 'bloodrequest'%}">Blood Request</a>
            <a href="{% url 'dashboard' %}" class="profile_nav" style="  color: white;
        text-decoration: none;
        margin: 0;
        max-height: 50px;
        max-width: 100px;">
        <img id="profile-photo-preview" 
     src="{% if user.profile.photo %}{{ user.profile.photo.url }}{% else %}{% static 'image/alt_profile.png' %}{% endif %}" 
     alt="profile image"  
     style="height: 50px; width: 50px; background: rgb(255, 175, 156); border: none; border-radius: 50%; margin: 0; padding: 0;"
     onerror="this.onerror=null; this.src='{% static 'image/alt_profile.png' %}';">

        </a>
        </div>
    </nav>
    <section>
          <div class="container">
        <h1>About Us</h1>
        <p>Welcome to Blood Bank Management System, your trusted partner in ensuring timely access to life-saving blood products. At Blood Bank Management System, we are committed to facilitating seamless blood donation, collection, processing, and distribution, thereby playing a pivotal role in enhancing healthcare outcomes and saving lives.</p>
        
        <h2>Our Mission</h2>
        <p>Our mission is to bridge the gap between blood donors and recipients by leveraging innovative technology and robust infrastructure to ensure a steady supply of safe and quality blood products. We strive to empower communities to participate in blood donation drives, fostering a culture of altruism and solidarity.</p>
        
        <h2>Our Vision</h2>
        <p>Our vision is to create a world where every individual has access to adequate and timely blood transfusions, irrespective of geographical barriers or socioeconomic factors. We aspire to be the cornerstone of blood banking solutions, setting benchmarks in efficiency, reliability, and ethical standards.</p>
        
        <h2>What Sets Us Apart</h2>
        <ul>
            <li>Technology-Driven Approach</li>
            <li>Commitment to Quality</li>
            <li>Community Engagement</li>
            <li>Collaborative Partnerships</li>
        </ul>
        
        <h2>Our Services</h2>
        <ol>
            <li>Donor Registration</li>
            <li>Blood Request Registration</li>
            <li>Provide details of the blood donor</li>
        </ol>
        
        <h2>Get Involved</h2>
        <p>Join us in our mission to save lives. Whether you're a potential donor, a healthcare provider, or a community organization, there are numerous ways to get involved and make a difference. Together, we can create a world where no one suffers due to a shortage of blood.</p>
        
        <p>Thank you for choosing Blood Bank Management System as your partner in saving lives. Your support fuels our commitment to excellence and drives us towards our shared vision of a healthier, brighter future.</p>
        
        {% comment %} <p><a href="contact.html">Contact Us</a> to learn more about how you can contribute or to inquire about our services.</p> {% endcomment %}
    </div>
    </section>
 

    <footer>
        <div class="footer-container">
            <div class="footer-section">
                <h3>Team Jay Nepal</h3>
            </div>
                
            </div>
      
            <div class="footer-bottom">
                <p>&copy; 2024 Team Jay Nepal. All rights reserved.</p>
            </div>
     </footer>

</body>
</html>

templates/bloodrequest.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blood Recipient Request</title>
    <style>
      body {
        font-family: Arial, sans-serif;
        background-color: #f4f4f4;
        margin: 0;
        padding: 0;
    }

    nav {
        background-color: #ff5b4f;
        overflow: hidden;
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 10px 20px;
    }

    .logo {
        color: white;
        text-decoration: none;
       font-size: 1.5em;
        margin: 0;
        padding: 0;
    }
    .logo img{
        max-height:80px ;
        margin: 0;
        padding: 0;
    }
    nav a {
        color: white;
        text-decoration: none;
        padding: 14px 16px;
    }

    nav a:hover {
        background-color: #ff7575;
        color: black;
    }
    footer {
        background-color:#17183b;
        color: #ffff;
        padding: 30px ;
        bottom: 0px;
    }
    
    .footer-container {
        display: flex;
        justify-content: space-around;
        
        margin: 0 auto;
    }
    
    .footer-section {
        text-align: left;
    }
    
    .footer-bottom {
        text-align: center;
        margin: 0px;
        padding-top: 0px;
        background-color:#17183b;
    }

    
    .footer-bottom p {
        margin: 0;
    }

    section {
        width: 500px;
        max-width: 900px;
        margin-top:100px;
        margin-left: 200px;
        font-size: larger;
        background-color: #fff;
        padding: 20px;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    label {
        display: block;
        margin-bottom: 8px;
    }

    input, select {
        width: 100%;
        padding: 10px;
        margin-bottom: 15px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

    button {
        background-color: #dc3545;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

    button:hover {
        background-color: #c82333;
    }
    .donor{
        display: flex;
        height: 100%;
        margin-bottom: 20px;
    }
    .donor img{
        height:400px;
        width:400px;
        margin-top:200px;
        margin-left:7px;
        

    }
    .messages{
        margin: 0;
        padding: 0;

    }
    .post-container {
      display: flex;
      gap: 30px;
    }
    
    .post {
      width: 300px;
      background-color: #fff;
      padding: 20px;
      border-radius: 8px;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
      transition: transform 0.3s ease-in-out;
    }
    
    .post:hover {
      transform: translateY(-5px);
    }
    
    .post h3 {
      margin-top: 0;
    }
    
    .post p {
      margin-bottom: 10px;
    }
    .posting{
      margin-left: 30px;
    }
    </style>

</head>
<body>
    <nav>
        <a class="logo" href="{% url 'landing_page'%}">
            <img src="{% static 'image/blood.png' %}" alt="" srcset="" />
          MeroBloodBank</a>
        <div>
            <a href="{% url 'about'%}">About</a>
            <a href="{% url 'donor'%}">Donor</a>
            <a href="{% url 'bloodrequest'%}">Blood Request</a>
            <a href="{% url 'dashboard' %}" class="profile_nav" style="  color: white;
            text-decoration: none;
            margin: 0;
            max-height: 50px;
            max-width: 100px;">
            <img id="profile-photo-preview" 
         src="{% if user.profile.photo %}{{ user.profile.photo.url }}{% else %}{% static 'image/alt_profile.png' %}{% endif %}" 
         alt="profile image"  
         style="height: 50px; width: 50px; background: rgb(255, 175, 156); border: none; border-radius: 50%; margin: 0; padding: 0;"
         onerror="this.onerror=null; this.src='{% static 'image/alt_profile.png' %}';">
    
            </a>
        </div>
    </nav>
  

 
    <div class="donor">
      <img src="{% static 'image/bloodrequest-removebg-preview.png' %}" alt="blood request" srcset=""/>
      
      
      <section>
          {% if messages %}
          <ul class="messages">
              {% for message in messages %}
                  <li{% if message.tags %} class="{{ message.tags }}"{% endif %}style=" background-color: #f8d7da; 
                  color: #721c24; 
                  padding: 10px;
                  margin-left:0; 
                  margin-bottom: 10px; 
                  width:450px;
                  text-align:center;
                  border: 1px solid #f5c6cb; 
                  border-radius: 50px 2px 50px 2px; 
                  list-style-type: none; ">{{ message }}</li>
              {% endfor %}
          </ul>
          {% endif %} 
          <form action="{% url 'bloodrequest'%}" method="post">
            {% csrf_token %}
            <label for="name">Patient Name:</label>
            <input type="text" id="name" name="name" required>

            <label for="Address">Address:</label>
            <input type="text" id="address" name="address" required>

            <label for="Age">Age:</label>
            <input type="number" id="address" name="Age" required>

            <label for="email">Email:</label>
            <input type="email" id="email" name="email" required>

            <label for="bloodType">Required Blood Type:</label>
            <select id="bloodType" name="bloodType" required>
                <option value="A+">A+</option>
                <option value="A-">A-</option>
                <option value="B+">B+</option>
                <option value="B-">B-</option>
                <option value="O+">O+</option>
                <option value="O-">O-</option>
                <option value="AB+">AB+</option>
                <option value="AB-">AB-</option>
            </select>

            <label for="phone">Phone Number:</label>
            <input type="tel" id="phone" name="phone" required>

            <label for="hospital">Hospital Name:</label>
            <input type="text" id="hospital" name="hospital" required>

            <label for="urgency">Urgency:</label>
            <select id="urgency" name="urgency" required>
            <option value="Immediate">Immediate</option>
            <option value="Non-urgent">Non-urgent</option>
            </select>

            <button type="submit">Submit Request</button>
        </form>
      
          </div>
         
      </section>
  </div>
    <div class="posting">
        <div class="donor-section">
            <div class="post-container">
              {% for donor in donors %}
                <div class="post">
                  <h3>{{ donor.Donor_Name }}</h3>
                  <p>
                    <strong>Age:</strong> {{ donor.Donor_Age }}
                  </p>
                  <p>
                    <strong>Address:</strong> {{ donor.Donor_Address }}
                  </p>
                  <p>
                    <strong>Blood Type:</strong> {{ donor.Donor_BloodType }}
                  </p>
                  <p>
                    <strong>Email:</strong> {{ donor.Donor_Email }}
                  </p>
                  <p>
                    <strong>Phone:</strong> {{ donor.Donor_Phone }}
                  </p>
                  <p>
                    <strong>Submission Date:</strong> {{ donor.Donor_DateTime }}
                  </p>
                </div>
              {% endfor %}
            </div>
          </div>
    
        </div>
    <footer>
        <div class="footer-container">
            <div class="footer-section">
                <h3>Team Jay Nepal</h3>
            </div>
                
            </div>
      
            <div class="footer-bottom">
                <p>&copy; 2024 Team Jay Nepal. All rights reserved.</p>
            </div>
     </footer> 
</body>
</html>

templates/bloodreuest.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blood Recipient Request</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }

        header {
            background-color: #c13d39;
            color: #fff;
            text-align: center;
            padding: 1em;
        }

        section {
            max-width: 600px;
            margin: 20px auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        label {
            display: block;
            margin-bottom: 8px;
        }

        input, select {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        button {
            background-color: #c13d39;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        button:hover {
            background-color: #c13d39;
        }
        a{
           
           font-size: xx-large;
           text-decoration: none;
           color: #f4f4f4;

       }
       .request-body{
        display:flex;
       }
       img{
         position: relative;
         left:10rem;
       }

    </style>
</head>
<body>
    

    <header>
        <a href="{% static 'css/index.css' %}"><strong>MeroBloodBank</strong></a>
        <h1>Blood Recipient Request</h1>
    </header>

    <div class="request-body">
        <img src="{%static'image/bloodrequest-removebg-preview.png'%}" alt="bloodRequestImage" srcset="">
    <section>
        <form action="#" method="post">
            <label for="name">Full Name:</label>
            <input type="text" id="name" name="name" required>

            <label for="Address">Address:</label>
            <input type="text" id="address" name="name" required>

            <label for="email">Email:</label>
            <input type="email" id="email" name="email" required>

            <label for="bloodType">Required Blood Type:</label>
            <select id="bloodType" name="bloodType" required>
                <option value="A+">A+</option>
                <option value="A-">A-</option>
                <option value="B+">B+</option>
                <option value="B-">B-</option>
                <option value="O+">O+</option>
                <option value="O-">O-</option>
                <option value="AB+">AB+</option>
                <option value="AB-">AB-</option>
            </select>

            <label for="phone">Phone Number:</label>
            <input type="tel" id="phone" name="phone" required>

            <label for="hospital">Hospital Name:</label>
            <input type="text" id="hospital" name="hospital" required>

            <button type="submit">Submit Request</button>
        </form>
    </section>
</div>
</body>
</html>

templates/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>MeroBloodBank</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/dashboard.css' %}" />
  </head>

  <body>
    <nav>
      <a class="logo" href="{% url 'landing_page' %}">
        <img src="{% static 'image/blood.png' %}" alt="" srcset="" />
        MeroBloodBank
      </a>
      <div>
        <a href="{% url 'about' %}">About</a>
        <a href="{% url 'donor' %}">Donor</a>
        <a href="{% url 'bloodrequest' %}">Blood Request</a>
        <a href="{% url 'dashboard' %}" class="profile_nav" style="  color: white;
        text-decoration: none;
        margin: 0;
        max-height: 50px;
        max-width: 100px;">
        <img id="profile-photo-preview" 
     src="{% if user.profile.photo %}{{ user.profile.photo.url }}{% else %}{% static 'image/alt_profile.png' %}{% endif %}" 
     alt="profile image"  
     style="height: 50px; width: 50px; background: rgb(255, 175, 156); border: none; border-radius: 50%; margin: 0; padding: 0;"
     onerror="this.onerror=null; this.src='{% static 'image/alt_profile.png' %}';">

        </a>
      </div>
    </nav>

    <div class="container">
      <h1>My Profile</h1>
      <div class="profile-photo">
        <img id="profile-photo-preview" src="{% if user.profile.photo %}{{ user.profile.photo.url }}{% else %}{% static 'image/alt_profile.png' %}{% endif %}" 
        alt="profile image" onerror="this.onerror=null; this.src='{% static 'image/alt_profile.png' %}';" >
    </div>
    <form id="upload-form" method="post" enctype="multipart/form-data" class="upload-form">
        {% csrf_token %}
        <p class="photo-uplaodd">
          
          <label for="id_photo" class="custom-file-upload">
              <input type="file" name="photo" id="id_photo" style="display: none;" onchange="previewProfilePhoto(event)">
              <i class="fas fa-upload"></i> Browse
          </label>
          <button type="submit">Upload Photo</button>
        </p>
    </form>
      <div class="profile-info">
        <label for="first_name">First Name:</label>
        <span>{{ user.first_name }}</span>
      </div>
      <div class="profile-info">
        <label for="last_name">Last Name:</label>
        <span>{{ user.last_name }}</span>
      </div>
      <div class="profile-info">
        <label for="username">Username:</label>
        <span>{{ user.username }}</span>
      </div>
      <div class="profile-info">
        <label for="email">Email:</label>
        <span>{{ user.email }}</span>
      </div>
      <a href="{% url 'logout' %}" class="btn-edit">Logout</a>
    </div>
    <div class="toggle-btn">
      <button onclick="toggleSection('donor')">Show Your donation</button>
      <button onclick="toggleSection('requestor')">Show your request</button>
    </div>
    <div class="dashboard">
      <div class="donor-section">
        <h2>Donation</h2>
        <div class="post-container">
          {% for donor in donors %}
            <div class="post">
              <h3>{{ donor.Donor_Name }}</h3>
              <p>
                <strong>Age:</strong> {{ donor.Donor_Age }}
              </p>
              <p>
                <strong>Address:</strong> {{ donor.Donor_Address }}
              </p>
              <p>
                <strong>Blood Type:</strong> {{ donor.Donor_BloodType }}
              </p>
              <p>
                <strong>Email:</strong> {{ donor.Donor_Email }}
              </p>
              <p>
                <strong>Phone:</strong> {{ donor.Donor_Phone }}
              </p>
              <p>
                <strong>Submission Date:</strong> {{ donor.Donor_DateTime }}
              </p>
              <button><a href="/donor/{{donor.id}}/edit_donor">Edit</a></button>
              <button><a href="/donors/{{donor.id}}/delete" style="text-decoration: none;">Delete</a></button> 
            </div>
          {% endfor %}
        </div>
      </div>

      <div class="requestor-section" style="display: none;">
        <h2>Requests</h2>
        <div class="post-container">
          {% for receipent in receipents %}
            <div class="post">
              <h3>{{ receipent.Receipent_Name }}</h3>
              <p><strong>Age:</strong> {{ receipent.Receipent_Age }}</p>
              <p><strong>Address:</strong> {{ receipent.Receipent_Address }}</p>
              <p><strong>Blood Type:</strong> {{ receipent.Receipent_BloodType }}</p>
              <p><strong>Email:</strong> {{ receipent.Receipent_Email }}</p>
              <p><strong>Phone:</strong> {{ receipent.Receipent_Phone }}</p>
              <p><strong>Hospital:</strong> {{ receipent.Receipent_Hospital }}</p>
              <p><strong>Submitted at:</strong>{{ receipent.Receipent_DateTime }}</p>
              <button><a href="/receipent/{{receipent.id}}/edit_receipent">Edit</a></button>
              <button><a href="/receipent/{{receipent.id}}/delete" style="text-decoration: none;">Delete</a></button> 
            </div>
          {% endfor %}
        </div>
      </div>
    </div>

    <footer>
      <div class="footer-container">
        <div class="footer-section">
          <h3>Team Jay Nepal</h3>
        </div>
      </div>

      <div class="footer-bottom">
        <p>&copy; 2024 Team Jay Nepal. All rights reserved.</p>
      </div>
    </footer>
    <script>
      function toggleSection(section) {
        const donorSection = document.querySelector('.donor-section')
        const requestorSection = document.querySelector('.requestor-section')
      
        if (section === 'donor') {
          donorSection.style.display = 'block'
          requestorSection.style.display = 'none'
        } else if (section === 'requestor') {
          donorSection.style.display = 'none'
          requestorSection.style.display = 'block'
        }
      }
      function previewProfilePhoto(event) {
        var input = event.target;
        var reader = new FileReader();
    
        reader.onload = function() {
            var profilePhotoPreview = document.getElementById('profile-photo-preview');
            profilePhotoPreview.src = reader.result;
        };
    
        reader.readAsDataURL(input.files[0]);
    }




      
    </script>
  </body>
</html>

templates/donor.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blood Donor Registration</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }

        nav {
            background-color: #ff5b4f;
            overflow: hidden;
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 10px 20px;
        }

        .logo {
            color: white;
            text-decoration: none;
           font-size: 1.5em;
            margin: 0;
            padding: 0;
        }
        .logo img{
            max-height:80px ;
            margin: 0;
            padding: 0;
        }
        nav a {
            color: white;
            text-decoration: none;
            padding: 14px 16px;
        }

        nav a:hover {
            background-color: #ff7575;
            color: black;
        }
        footer {
            background-color:#17183b;
            color: #ffff;
            padding: 30px ;
            bottom: 0px;
        }
        
        .footer-container {
            display: flex;
            justify-content: space-around;
            
            margin: 0 auto;
        }
        
        .footer-section {
            text-align: left;
        }
        
        .footer-bottom {
            text-align: center;
            margin: 0px;
            padding-top: 0px;
            background-color:#17183b;
        }
    
        
        .footer-bottom p {
            margin: 0;
        }
    
        section {
            width: 500px;
            max-width: 900px;
            margin-top:100px;
            margin-bottom:50px;
            margin-left: 200px;
            font-size: larger;
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        label {
            display: block;
            margin-bottom: 8px;
        }

        input, select {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        button {
            background-color: #dc3545;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        button:hover {
            background-color: #c82333;
        }
        .donor{
            display: flex;
        }
        .donor img{
            height:400px;
            width:400px;
            margin-top:50px;
            margin-left:7px;
            

        }
        .messages{
            margin: 0;
            padding: 0;

        }
      
    </style>
</head>
<body>
    <nav>
        <a class="logo" href="{% url 'landing_page'%}">
            <img src="{% static 'image/blood.png' %}" alt="" srcset="" />
          MeroBloodBank</a>
        <div>
            <a href="{% url 'about'%}">About</a>
            <a href="{% url 'donor'%}">Donor</a>
            <a href="{% url 'bloodrequest'%}">Blood Request</a>
            <a href="{% url 'dashboard' %}" class="profile_nav" style="  color: white;
        text-decoration: none;
        margin: 0;
        max-height: 50px;
        max-width: 100px;">
        <img id="profile-photo-preview" 
     src="{% if user.profile.photo %}{{ user.profile.photo.url }}{% else %}{% static 'image/alt_profile.png' %}{% endif %}" 
     alt="profile image"  
     style="height: 50px; width: 50px; background: rgb(255, 175, 156); border: none; border-radius: 50%; margin: 0; padding: 0;"
     onerror="this.onerror=null; this.src='{% static 'image/alt_profile.png' %}';">

        </a>
        </div>
    </nav>
  

    <div class="donor">
        <img src="{% static 'image/blooddonor2.png' %}" alt="blood Donor" srcset="" />
        
        
        <section>
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}style=" background-color: #f8d7da; 
                    color: #721c24; 
                    padding: 10px;
                    margin-left:0; 
                    margin-bottom: 10px; 
                    width:450px;
                    text-align:center;
                    border: 1px solid #f5c6cb; 
                    border-radius: 50px 2px 50px 2px; 
                    list-style-type: none; ">{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %} 
            <form action="{% url 'donor'%}" method="post">
                
                {% csrf_token %}
                <label for="name">Full Name:</label>
                <input type="text" id="name" name="name" required>

                <label for="Age">Age:</label>
                <input type="number" id="Age" name="Age" required min="18" max="70">

                <label for="Address">Address:</label>
                <input type="text" id="Address" name="Address" required>

                <label for="bloodType">Blood Type:</label>
                <select id="bloodType" name="bloodType" required>
                    <option value="A+">A+</option>
                    <option value="A-">A-</option>
                    <option value="B+">B+</option>
                    <option value="B-">B-</option>
                    <option value="O+">O+</option>
                    <option value="O-">O-</option>
                    <option value="AB+">AB+</option>
                    <option value="AB-">AB-</option>
                </select>

                <label for="phone">Phone Number:</label>
                <input type="tel" id="phone" name="phone" required>

                <button type="submit">Submit</button>

            </form>
        
            </div>
           
        </section>
    </div>
<footer>
    <div class="footer-container">
        <div class="footer-section">
            <h3>Team Jay Nepal</h3>
        </div>
            
        </div>
  
        <div class="footer-bottom">
            <p>&copy; 2024 Team Jay Nepal. All rights reserved.</p>
        </div>
 </footer>
  <script>
                {% if messages and messages|length > 0 and messages.0.tags == 'success' %}
                    handleSuccess();
                {% endif %}
            
                function handleSuccess() {
                    alert('Form submitted successfully!');
                }
            </script>
</body>
</html>